### ISSUE TITLE
Missing ReportPortal in Testing

### ISSUE THREAD

**Issue by DzmitryHumianiuk** [epam/epam.github.io#1]
ReportPortal has private repo in epam org,
it deprecated, since all repos are in https://github.com/reportportal

**Comment by ghost** [comment]
Sorry, what's the question? We do not show private repositories (because they are well... private).
Shall we be showing the separate organization? Sure thing. We are trying to figure out how to represent the dozens of the repos in there in some coherent manner. Stay tuned.
